package selenium;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class GeneratedTestCases {
    // Generated by Selenium IDE
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testNavbar() {
        driver.get("https://www.il-colosseo.it/es/");
        driver.manage().window().setSize(new Dimension(1696, 1026));
        driver.findElement(By.linkText("Info Boletos")).click();
        driver.findElement(By.linkText("Los subterráneo")).click();
        driver.findElement(By.linkText("Los Foros")).click();
        driver.findElement(By.linkText("El Coliseo de noche")).click();
        driver.findElement(By.linkText("Visitas guiadas")).click();
        driver.findElement(By.linkText("Como llegar")).click();
        driver.findElement(By.linkText("Navidad 2023")).click();
        driver.findElement(By.linkText("Gratis")).click();
        driver.findElement(By.linkText("Exposiciones")).click();
        driver.findElement(By.linkText("Niños")).click();
        driver.findElement(By.linkText("Vaticano")).click();
        driver.findElement(By.linkText("FAQ")).click();
        driver.findElement(By.linkText("Contactos")).click();
    }
}
